services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - db
    environment:
      DB_CONN: host=db user=testuser password=testpass dbname=testdb sslmode=disable
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8080
    ports:
      - "8081:8081"

  backend-tester:
    build:
      context: ./backend-tester
    container_name: backend-tester
    depends_on:
      - backend
    environment:
      BACKEND_URL: http://backend:8080
    networks:
      - default
    command: ["./backend-tester"]
